# Cognito-autentikaatio emaililla ja passwordilla
# Jos haluat lisätä sosiaalisen autentikaation (esim. Google)
# katso mallia tästä tiedostosta:
# https://github.com/ParthTrambadiya/congito-iac-sf/blob/main/serverless.yml
#
#org: omatunnus
service: aws-teht3-graphql-cognito-auth
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  environment: # ympäristömuuttujat
    user_pool_id: { Ref: UserPool } # cogniton user pool
    client_id: { Ref: UserClient } # cogniton client id      
    DDB_TABLE: StudentTable #${self:service}-studentTable-${sls:stage}   #StudentTable # Käytämme koodissa ympäristömuuttujaa DDB_TABLE
  iam:
    role:
      statements:
        - Effect: Allow
          Action: # lambda-funktioille oikeudet käyttää cognitoa
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - dynamodb:*
          Resource: "*"
  httpApi:
    cors: true
    authorizers:
      PrivateAuthorizer: # Cogniton authorizerin nimi
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp."
              - "${opt:region, self:provider.region}"
              - ".amazonaws.com/"
              - Ref: UserPool
        audience:
          - Ref: UserClient

functions:
  
  signupUser: # rekisteröityminen eli tunnareiden luonti
    handler: user/signup.handler
    events:
      - httpApi:
          path: /user/signup
          method: post
  
  loginUser: # sisäänkirjautuminen
    handler: user/login.handler
    events:
      - httpApi:
          path: /user/login
          method: post

  dographql:
    handler: apolloserver.handler # serveritiedosto on ainoa lambda-funktio
    events:
      - httpApi:
          path: /graphql
          method: post # yleensä apollo server käyttää post-metodia
          authorizer: PrivateAuthorizer
      - httpApi:
          path: /graphql
          method: get # get-metodia voi käyttää hakukyselyihin, mutta ei mutaatioihin 

  privateAPI: # suojattu funktio ja reitti
    handler: user/private.handler
    events:
      - httpApi:
          path: /user/private
          method: post
          authorizer: PrivateAuthorizer # suojaus
    
resources: # resurssit eli palvelut oletuspalveluiden lisäksi
  Resources:
    UserPool: # cognito userpool
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: serverless-auth-pool
        Schema: # käyttäjän tietojen skeema cognitossa. Tässä pelkkä email
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy: # salasanan ominaisuudet
            MinimumLength: 6
        AutoVerifiedAttributes: ["email"] # email validoidaan

    UserClient: # cognito userpoolin client
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5 # token validi 5 tuntia
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH" # tavallinen authorisaatio emaililla ja salasanalla

    
    # Tietokannan käyttöönotto Cloudformation-syntaksilla
    StudentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: studentcode
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: studentcode
            KeyType: HASH
        TableName: StudentTable #${self:service}-studentTable-${sls:stage}
