POST https://vr6mgijfvf.execute-api.eu-north-1.amazonaws.com/user/signup
Content-Type: application/json

{
  "email": "AA4598@student.jamk.fi",
  "password": "topsecret",
  "name": "Timo Laakkonen"  
}